services:
  backend:
    container_name: binari-backend
    build:
      context: .
      dockerfile: Dockerfile.backend
    env_file:
      - .env
    environment:
      - VIRTUAL_HOST=rfi.b4service.it
      - VIRTUAL_PATH=/api
      - VIRTUAL_PORT=8000
      - LETSENCRYPT_HOST=rfi.b4service.it
    expose:
      - "8000"
    networks:
      - service-tier
    restart: unless-stopped

  frontend:
    container_name: binari-frontend
    build:
      context: ./frontend-react
      dockerfile: ../Dockerfile.frontend
    environment:
      - VIRTUAL_HOST=rfi.b4service.it
      - LETSENCRYPT_HOST=rfi.b4service.it
      - VIRTUAL_PORT=80
      - VIRTUAL_PATH=/
      - REACT_APP_API_BASE=/api
    networks:
      - service-tier
    restart: unless-stopped

networks:
  service-tier:
    external: true
